[project]
name = "wtm-library-ms-milasha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Milasha Ninnadi Subasinghe", email = "milasha69official@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-import-export>=4.4.1",
]

[project.scripts]
wtm-library-ms-milasha = "wtm_library_ms_milasha:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
